"""empty message

Revision ID: a7db883caa60
Revises: 864c748de76d
Create Date: 2024-11-21 15:08:11.034252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7db883caa60'
down_revision = '864c748de76d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_Name', sa.String(length=120), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('last_Name', sa.String(length=120), nullable=False, server_default=''))
    # Eliminar el valor por defecto para futuras inserciones
    op.alter_column('user', 'first_Name', server_default=None)
    op.alter_column('user', 'last_Name', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_Name')
        batch_op.drop_column('first_Name')

    # ### end Alembic commands ###
